### PR TITLE
Add CMake to fortran_udunits2

### PR DESCRIPTION
**Pull request by mathomp4**
This is a WIP PR to add CMake to fortran_udunits2. I've done a few things:

1. "Borrowed" the [`Findudunits.cmake`](https://github.com/NOAA-EMC/CMakeModules/blob/develop/Modules/Findudunits.cmake) file from NOAA-EMC (cc @climbfuji)
2. Edited the `Findudunits.cmake` file because Baselibs only provides a static `libudunits2.a` and my attempts to link to it (see below) were failing since the current one is static only
3. Used the [trick @scivision code](https://www.scivision.dev/cmake-auto-gitignore-build-dir/) to ignore build and install directories (much like we do in GEOS)
4. Added a `.gitignore` so that common editor temp files don't get committed.
5. Added an `.editorconfig` file because Vim was unhappy for some reason without it!
6. Ran `fprettify` on some of the Fortran code because my editor was *not* happy.
7. Converted all the `FORTRAN` to `Fortran` to make @tclune happy. 😄 

I think this is good to go.

### CODE REVIEW

**Comment by mathomp4** [comment]
Well now I'm confused. I just pushed some updates to [my branch on my fork](https://github.com/mathomp4/fortran_udunits2/tree/feature/add-cmake), but GitHub isn't showing them here.

**Comment by mathomp4** [comment]
~Oh, and there are lots of debugging prints in this currently. I figure once all is well, I can do a cleanup.~

Removed the debug prints

**Comment by mathomp4** [comment]
@mfvalin FYI: We might be sending more your way as we work through trying to use the code. If at some point you'd prefer us to fork and become the "primary" repo for this, just let me know. (Don't want to burden you with PRs if this is more of a side project.)

**Comment by mfvalin** [comment]
do you have any preference ?
if you are likely to add to the project and improve it, it might be the logical way to go for you to become the "primary" repository .
i would then just point users  to the new "primary repository" should they want to stay in sync
(and i would do the same on my home system)

**Comment by mathomp4** [comment]
@mfvalin I had a conversation with some higher ups and it's possible that we might have to actually write our own new interface code due to NASA IP/licensing issues (I am not a lawyer caveats). 

But your work will at least let us do some testing/prototyping so we understand how to even use Udunits which is new to us. (Plus, we think we might need extra interfaces beyond what you have due to how our code works.)

Indeed, our hope is that maybe we can write something new to give to Unidata (@semmerson, I guess in this case) so that neither of us have to maintain anything like this and we all get Fortran free!

Still, if I find any issues with the current code as we explore Fortran+UDUNITS2 I'll be sure to pass on any bug fixes.

**Comment by ghost** [comment]
@mfvalin I'm surprised that you wrote there are licensing issues because the UDUNITS 2 license allows you to do pretty much whatever you want with the code.

**Comment by mfvalin** [comment]
@mathomp4 the whole point of that kind of licensing is to share the code so that everybody benefits from everybody's work

**Comment by mathomp4** [comment]
@mfvalin I can say in my experience, NASA is...interesting when it comes to this sort of thing (work product, etc). It's above my paygrade, but I know we need to be careful. I'm pretty sure I can build your code as it is "external" to our model, that is fine. In my library stack it is just a submodule so I'm sort of not "including" it in our code base. 

But as there is no license file in here, I'm not sure what the lawyers would say if suddenly it was in our, say, Apache 2 code.

I'm always confused by this stuff! 😕 And it's possible I'm overthinking it. But it is lawyers so overthinking is usually where you have to start...

**Comment by mfvalin** [comment]
@mathomp4  i added a LICENSE file (BSD 3 clause), explicitly referenced in the code
(more along the usual way to do it)

**Pull request merged**
